title: Your site title
description: Your site's one-sentence description

# add any site-wide meta tags here
meta:
  og:type: site

# this should *not* include the trailing slash
url: ''

stylesheets:
  - /assets/css/uswds.css

scripts:
  - /assets/js/uswds.js

exclude:
  - '.sass-cache'
  - '.ruby-version'
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md
  - package.json
  - vendor
  - node_modules
